#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

tput setaf 2;
echo "[Husky]: pre-commit"
echo "[Husky]: run lint"
tput sgr0;

npm run lint

tput setaf 2;
echo "[Husky]: run prettier-check"
tput sgr0;

npm run prettier-check